apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/tmp/data02"
    type: DirectoryOrCreate
