apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  selector:
    app: petclinic
  ports:
    - name: http
      port: 8080
      # targetPort: 8080
      # nodePort: 31080
  type: LoadBalancer
